spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
    open-in-view: false

kakao:
  client-id: ${KAKAO_API_KEY}
  client-secret: ${KAKAO_API_SECRET_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URL}
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com

jwt:
  access_expiration_time: ${ACCESS_EXP_TIME}
  refresh_expiration_time: ${REFRESH_EXP_TIME}
  secret: ${JWT_SECRET}